# Site
name: "Deezigns"
title: "Deezigns<sub>by Dee Hamlin</sub>"
description: "Deezigns by Dee Hamlin comes from a life of creating and exploring possibilities in texture, color, contrast, fibers, and with just about any medium I can get my hands on."
logo: 'assets/images/DeezignsLOGO.jpg'
favicon: ''
baseurl: ''
google_analytics: ''
include: ["_pages"]
permalink: /:title/

defaults:
  -scope:
    path: "assets/images"
  values:
    image: true

# Authors
authors:
  dee:
    name: Deanna Hamlin
    display_name: Dee Hamlin
    email: deezignsbydeehamlin@gmail.com
    avatar: 'assets/images/Deemasked.jpg'
    description: "deezignsbydeehamlin@gmail.com"
  ben:
    name: Benjamin Hamlin
    display_name: kaptinbadrukk314
    gravatar: f783aabb998dccdc83e001d95cce1339
    email: kaptinbadrukk314@gmail.com
    web: https://linktr.ee/KaptinBadrukk314
    description: "Software engineer, web developer, and variety streamer on Twitch. Assisted in creating and maintaining the website."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
#adsense-data-ad-client: "ca-pub-3412143450191416"
#gravadsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

#theme: jekyll-theme-cayman
